-- 1. Students from India

SELECT * FROM Students
WHERE Country = 'India';

-- 2. Courses with Price Greater Than 70

SELECT Course_Name, Price FROM Courses
WHERE Price > 70;

-- 3. Total Number of Students

SELECT COUNT(*) AS Total_Students
FROM Students;

-- 4. Total Enrollments per Course

SELECT CourseID, COUNT(*) AS Total_Enrollments
FROM Enrollments
GROUP BY CourseID;

-- 5. Student Name with Course Name

SELECT s.Name, c.Course_Name FROM Enrollments e
JOIN Students s
ON e.StudentID = s.StudentID
JOIN Courses c
ON e.CourseID = c.CourseID;

-- 6. Courses Sorted by Price

SELECT Course_Name, Price FROM Courses
ORDER BY Price DESC;

-- 7. Most Popular Course

SELECT TOP 1 c.Course_Name, COUNT(*) AS Total_Enrollments
FROM Enrollments e
JOIN Courses c
ON e.CourseID = c.CourseID
GROUP BY c.Course_Name
ORDER BY Total_Enrollments DESC;

-- 8. Students Enrolled in Multiple Courses

SELECT StudentID, COUNT(CourseID) AS Total_Courses
FROM Enrollments
GROUP BY StudentID
HAVING COUNT(CourseID) > 1;

-- 9. Revenue Generated by Each Course

SELECT c.Course_Name,
COUNT(e.EnrollmentID) * c.Price AS Total_Revenue
FROM Courses c
JOIN Enrollments e
ON c.CourseID = e.CourseID
GROUP BY c.Course_Name, c.Price;

-- 10. Country-wise Student Count

SELECT Country, COUNT(*) AS Total_Students
FROM Students
GROUP BY Country
ORDER BY Total_Students DESC;

-- 11. Courses with No Enrollments

SELECT c.Course_Name
FROM Courses c
LEFT JOIN Enrollments e
ON c.CourseID = e.CourseID
WHERE e.CourseID IS NULL;

-- 12. Student Who Enrolled in the Most Courses

SELECT TOP 1 s.Name, COUNT(e.CourseID) AS Total_Courses
FROM Students s
JOIN Enrollments e
ON s.StudentID = e.StudentID
GROUP BY s.Name
ORDER BY Total_Courses DESC;